### PR TITLE
optional (useless) vis

### PR DESCRIPTION
**Pull request by Neimhin**

### CODE REVIEW

**Comment by Neimhin** [comment]
You may be able to use my build of sdl2: https://scss.tcd.ie/~nrobinso/sdl.zip

```bash
mkdir ~/local; cd ~/local
curl https://scss.tcd.ie/~nrobinso/sdl.zip
unzip sdl.zip
export  PATH=$PATH:`realpath ./bin`
pip install pygame
```

**Comment by tedski999** [comment]
Will this be redundant with your web server approach for introspection? I'd be happy to help develop a example Server and Client implementations that provide such web interfaces.

**Comment by Neimhin** [comment]
> Will this be redundant with your web server approach for introspection? I'd be happy to help develop a example Server and Client implementations that provide such web interfaces.

Yes, the web approach is much better. Simply attach to the pi with `ssh -L 8080:localhost:8080` or similar and serve up the interesting data.

**Comment by tedski999** [comment]
Implemented in c8b8d46

**Pull request closed without merging**
